import tellurium as te
import pandas as pd

df = pd.read_csv("experimentalCondition_Froehlich_CellSystems2018.tsv", sep="\t")
print(df)
# model = te.loadSBMLModel("model_Froehlich_CellSystems2018.xml")
# print(model.getFloatingSpeciesIds())
# print(model.getBoundarySpeciesIds())
# print(model.getAssignmentRuleIds())
# print(model.getRateRuleIds())
# print(model.getKineticLawIds())
# print(model.getReactionIds())
# print(model.getSpeciesIds())
# print(model.getParameterIds())
# print(model.getEventIds())
# print(model.getNotes())
# print(model.getCompartmentIds())
# print(model.getFloatingSpeciesConcentrations())
# print(model.getBoundarySpeciesConcentrations())
# print(model.getAssignmentRuleValues())
# print(model.getRateRuleValues())
# print(model.getKineticLawValues())
# print(model.getReactionValues())
# print(model.getSpeciesValues())
# print(model.getParameterValues())
# print(model.getEventValues())
# print(model.getCompartmentValues())
convert_to_antimony = te.sbmlToAntimony("model_Froehlich_CellSystems2018.xml")
print(convert_to_antimony[0:200000])
save_to_file = open("model_Froehlich_CellSystems2018.ant", "w")
save_to_file.write(convert_to_antimony)
save_to_file.close()